Create acc
assist-software/internship-2022-august-fe1 pull request #2
Opened 2022-08-10 06:27 UTC by CojocaruAndrei

2022-08-10 20:44 UTC, petricafinaga requested changes

2022-08-10 20:44 UTC, petricafinaga commented on src/App.js
> +import "./app.scss";
I think you should add a line break here as suggested in best practices ;)

2022-08-10 20:44 UTC, petricafinaga commented on src/pages/CreateAccount/CreateAccount.js
> +import Button from "@mui/material/Button";
It's better to have imports from libraries at the top of the page, and imports from yours custom components should came after

2022-08-10 20:44 UTC, petricafinaga commented on src/pages/CreateAccount/CreateAccount.js
> +  const emailValidations = () => {
Maybe we can move this method into some separate service, it will be easier to read the components code

2022-08-10 20:44 UTC, petricafinaga commented on src/pages/CreateAccount/CreateAccount.js
> +    const regPass = /^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{8,}$/;
And also this whole method can be split into two methods, one for email validation, and one for password validation

2022-08-10 20:44 UTC, petricafinaga commented on src/pages/CreateAccount/CreateAccount.js
> +                color: "red",
For this message style I think you can add some class, and just use the same style for all, in order to remove the duplicated code

2022-08-10 20:44 UTC, petricafinaga commented on src/pages/CreateAccount/createAccount.scss
> +}
We should add always a new line after the last line of code at the end of the file

2022-08-10 20:44 UTC, petricafinaga commented on src/pages/CreateAccount/createAccount.scss
> +
This file can be formatted better, to look more 'pretty'

2022-08-11 08:40 UTC, BiancaDianaAlexiuc commented on src/pages/CreateAccount/createAccount.scss
> +align-self: center;
Pay a bit more attention to the code indentation of the SCSS files to keep a consistent indentation.

2022-08-11 13:33 UTC, petricafinaga approved these changes

2022-08-11 13:35 UTC, merged