Login, Forgot password, Reset password pages, import axios at Create …
assist-software/internship-2022-august-fe1 pull request #4
Opened 2022-08-16 06:31 UTC by CojocaruAndrei

…Account and Login

2022-08-16 07:18 UTC, BiancaDianaAlexiuc approved these changes

2022-08-16 07:41 UTC, petricafinaga requested changes

2022-08-16 07:41 UTC, petricafinaga commented on src/pages/CreateAccount/CreateAccount.js
> +  console.log("isCreate", isCreate);
This log also can be removed

2022-08-17 06:16 UTC, petricafinaga approved these changes

2022-08-17 06:16 UTC, petricafinaga commented on src/Service/axios.js
> +
I think this file can be removed

2022-08-17 06:19 UTC, merged